# Training defaults for metabolite (large graphs + conditioning)
n_epochs: 2000
batch_size: 32
lr: 2.0e-5
clip_grad: null
save_model: True
num_workers: 0
ema_decay: 0.999
progress_bar: true
weight_decay: 1.0e-12
optimizer: adamw
seed: 0
